kind: Pod
apiVersion: v1
metadata:
  name: csi-pod 
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: csi-pvc
      command: [ "sleep", "1000000" ]
  volumes:
    - name: csi-pvc
      persistentVolumeClaim:
        claimName: csi-pvc-restore